# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Deploy Javadoc

on:
  push:
    branches:
      -master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Javadoc
      uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 17
          target-folder: javadoc 
          project: maven
